app:
  name: "RAG Pipeline"
  host: 0.0.0.0
  port: 8000
  eager_init: false
logging:
  level: INFO
database:
  driver: postgres
  # Prefer DB_URL in .env. These fields are fallbacks and will be overridden by DB_URL when set.
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  table: properties
  id_column: id
  columns:
    - property_title
    - property_description
    - emirate
    - city
    - district
    - rent_charge

chunking:
  chunk_size: 500
  chunk_overlap: 50
  unit: token # "token" or "char"

embedding:
  provider: google
  model: gemini-embedding-001
  api_key: ${GOOGLE_API_KEY}
  batch_size: 64

vector_db:
  provider: elasticsearch
  hosts:
    - ${ELASTIC_HOST}
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  index: rag_properties
  similarity: cosine
  refresh_on_write: false
  dims: null # set to an integer to skip probing embedding dimension

retrieval:
  top_k: 5
  num_candidates_multiplier: 8
  filter_fields:
    - city
    - emirate
    - property_type_id

llm:
  provider: google
  model: gemini-2.5-flash-lite
  temperature: 0.2
  max_output_tokens: 1024

ingestion:
  batch_size: 500
