app:
  name: "RAG Pipeline"
  host: 0.0.0.0
  port: 8080
  eager_init: false

logging:
  level: DEBUG  # DEBUG level for comprehensive logging (shows all logs)

database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  table: properties
  id_column: id
  
  # Status filter configuration - filters which records to process
  status_filter:
    enabled: true
    field: property_status
    value: listed
  
  # Table relations configuration - defines foreign key JOINs and child relations
  relations:
    # Many-to-one relations (LEFT JOIN in main query)
    - name: property_type
      relation_type: many_to_one
      foreign_key: property_type_id
      reference_table: property_types
      reference_column: id
      fields_to_fetch:
        - name
      alias: property_type_name
      
    - name: rent_type
      relation_type: many_to_one
      foreign_key: rent_type_id
      reference_table: property_rent_types
      reference_column: id
      fields_to_fetch:
        - name
      alias: rent_type_name
    
    # One-to-many relations (separate query)
    - name: media
      relation_type: one_to_many
      foreign_key: propertyId
      reference_table: property_media
      reference_column: id
      fields_to_fetch:
        - file_name
        - thumbnail_url
        - id
      alias: media
      order_by: order
      limit: 5
  
  # Boolean fields configuration - all boolean fields with display labels (domain-agnostic)
  boolean_fields:
    gym_fitness_center: "Gym"
    swimming_pool: "Pool"
    maids_room: "Maid's Room"
    security_available: "Security"
    concierge_available: "Concierge"
    central_ac_heating: "Central AC"
    elevators: "Elevators"
    balcony_terrace: "Balcony"
    storage_room: "Storage"
    laundry_room: "Laundry"
    childrens_play_area: "Children's Play Area"
    bbq_area: "BBQ Area"
    pet_friendly: "Pet-Friendly"
    smart_home_features: "Smart Home"
    waste_disposal_system: "Waste Disposal"
    power_backup: "Power Backup"
    mosque_nearby: "Mosque Nearby"
    beach_access: "Beach Access"
    jogging_cycling_tracks: "Jogging/Cycling Tracks"
    chiller_included: "Chiller Included"
    sublease_allowed: "Sublease Allowed"
  
  # Priority features (high priority for filtering and display)
  priority_features:
    - swimming_pool
    - pet_friendly
    - gym_fitness_center
    - parking
    - balcony_terrace
  
  # Location field hierarchy (from broad to specific) - domain-agnostic
  location_hierarchy:
    - emirate        # Level 1: Country/Region/State
    - city           # Level 2: City
    - community      # Level 3: Community/Neighborhood/District
    - subcommunity   # Level 4: Sub-area/Locality
    - building_name  # Level 5: Building/Complex
  
  # Display configuration (simple direct values)
  display:
    currency: "AED"
    measurement_unit: "square feet"
  
  # Primary field for display in logs (generic - change per domain)
  primary_display_field: "property_title"  # For US: "listing_name", For UK: "property_name"
  
  # Pricing field for aggregations (generic - change per domain)
  pricing_field: "rent_charge"  # For US: "monthly_rent", For UK: "rent_pcm"
  
  # Filter priority groups (for retrieval optimization)
  filter_priority_groups:
    location:
      - emirate
      - city
      - community
      - subcommunity
      - nearby_landmarks
      - public_transport_type
    budget:
      - rent_charge
      - security_deposit
      - maintenance_charge
    property_type:
      - property_type_name
    rooms:
      - number_of_bedrooms
      - number_of_bathrooms
    furnishing:
      - furnishing_status
    lease:
      - lease_duration
      - rent_type_name
    availability:
      - available_from
  
  # Boosting configuration (optional - disable for domains without boosting)
  boosting:
    enabled: true  # Set to false for non-boosted domains (products, jobs, etc.)
    fields:
      premium: "premiumBoostingStatus"
      carousel: "carouselBoostingStatus"
      verification: "bnb_verification_status"
    active_values:
      premium: "Active"
      carousel: "Active"
      verification: "verified"
    boost_weights:
      premium: 0.15
      carousel: 0.1
      verification: 0.15
      all_three: 0.2  # Additional boost when all three are active
  
  # Query patterns (for special query handling)
  query_patterns:
    best_property:
      - "best"
      - "top"
      - "premium"
      - "featured"
      - "recommended"
      - "highest quality"

  # Field columns list
  columns:
    - id
    - property_title
    - property_description
    - property_type_id
    - furnishing_status
    - number_of_bathrooms
    - number_of_bedrooms
    - property_size
    - year_built
    - floor_level
    - emirate
    - city
    - community
    - subcommunity
    - building_name
    - apartment_unit_number
    - nearby_landmarks
    - plot_number
    - developer_name
    - rent_type_id
    - rent_charge
    - lease_duration
    - payment_terms
    - sublease_allowed
    - lease_start_date
    - lease_end_date
    - security_deposit
    - setup_grace_period
    - maintenance_charge
    - maintenance_covered_by
    - parking
    - swimming_pool
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - waste_disposal_system
    - power_backup
    - mosque_nearby
    - beach_access
    - jogging_cycling_tracks
    - property_view_id
    - unit_number
    - public_transport_type
    - retail_shopping_access
    - available_from
    - tenancy_start_date
    - listing_date
    - chiller_included
    - property_status
    - premiumBoostingStatus
    - carouselBoostingStatus
    - bnb_verification_status
    - media

  # ✅ Semantic fields for embedding (descriptive text content)
  embedding_columns:
    - property_title
    - property_description
    - building_name
    - nearby_landmarks
    - developer_name
    - floor_level
    - apartment_unit_number

  # ✅ Filters for structured fields
  field_types:
    # Text fields for embedding
    property_title: text
    property_description: text
    building_name: text
    nearby_landmarks: text
    developer_name: text
    floor_level: text
    apartment_unit_number: text

    # Location fields
    emirate: keyword
    city: keyword
    community: keyword
    subcommunity: keyword

    # Property type and status
    property_type_name: keyword
    furnishing_status: keyword
    rent_type_name: keyword
    property_status: keyword
    maintenance_covered_by: keyword

    # Numeric fields
    number_of_bedrooms: integer
    number_of_bathrooms: integer
    property_size: float
    year_built: integer
    plot_number: integer
    unit_number: integer
    rent_charge: float
    security_deposit: float
    maintenance_charge: float

    # Boosting and verification
    bnb_verification_status: keyword
    premiumBoostingStatus: keyword
    carouselBoostingStatus: keyword

    # Boolean amenities
    maids_room: boolean
    security_available: boolean
    concierge_available: boolean
    central_ac_heating: boolean
    elevators: boolean
    balcony_terrace: boolean
    storage_room: boolean
    laundry_room: boolean
    gym_fitness_center: boolean
    childrens_play_area: boolean
    bbq_area: boolean
    pet_friendly: boolean
    smart_home_features: boolean
    waste_disposal_system: boolean
    power_backup: boolean
    mosque_nearby: boolean
    beach_access: boolean
    jogging_cycling_tracks: boolean
    chiller_included: boolean
    sublease_allowed: boolean

    # JSON fields
    parking: json
    swimming_pool: json
    public_transport_type: json
    retail_shopping_access: json
    media: json

    # Date fields (stored as strings for filtering)
    lease_start_date: keyword
    lease_end_date: keyword
    available_from: keyword
    tenancy_start_date: keyword
    listing_date: keyword

    # Other fields
    lease_duration: keyword
    payment_terms: keyword
    setup_grace_period: keyword
    property_view_id: keyword

chunking:
  chunk_size: 800 # Optimized for property descriptions with full context
  chunk_overlap: 100 # Increased overlap for better continuity between chunks
  unit: token

embedding:
  provider: google
  model: gemini-embedding-001 # Use specified model
  api_key: ${LLM_MODEL_API_KEY}
  batch_size: 10 # Reduce from 64 to avoid rate limits

vector_db:
  provider: elasticsearch
  hosts:
    - ${VECTOR_DB_HOST}
  username: ${VECTOR_DB_USERNAME}
  password: ${VECTOR_DB_PASSWORD}
  index: rag_properties
  similarity: cosine
  refresh_on_write: false
  dims: 3072 # Correct dimensions for gemini-embedding-001
  mapping_properties_key: properties
  # Elasticsearch 8.17.1 configuration
  index_settings:
    number_of_shards: 1
    number_of_replicas: 0

retrieval:
  top_k: 12 # Increased for better results
  num_candidates_multiplier: 8 # Reduced for speed while maintaining quality
  filter_fields:
    # Location filters
    - emirate
    - city
    - community
    - subcommunity

    # Property type and status
    - property_type_name
    - furnishing_status
    - rent_type_name
    - property_status
    - maintenance_covered_by

    # Numeric filters
    - number_of_bedrooms
    - number_of_bathrooms
    - property_size
    - year_built
    - rent_charge
    - security_deposit
    - maintenance_charge

    # Boosting and verification
    - bnb_verification_status
    - premiumBoostingStatus
    - carouselBoostingStatus

    # Boolean amenities
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - waste_disposal_system
    - power_backup
    - mosque_nearby
    - beach_access
    - jogging_cycling_tracks
    - chiller_included
    - sublease_allowed

    # Date filters
    - available_from
    - lease_start_date
    - lease_end_date
    - tenancy_start_date
    - listing_date

    # Other filters
    - lease_duration
    - developer_name

llm:
  provider: google
  model: gemini-2.5-flash-lite
  temperature: 0.2
  max_output_tokens: 2048
  
  # Query handling - enable/disable features (NO hardcoded lists!)
  query_handling:
    use_llm_classification: true  # Let LLM classify queries using intelligence
    enable_price_aggregation: true  # Enable average price calculations
    enable_knowledge_search: true  # Enable web search for knowledge queries
    enable_requirement_gathering: true  # Enable save requirements feature
    enable_context_validation: true  # Enable response validation against chunks
    validation_tolerance: 0.05  # 5% tolerance for numeric validation

ingestion:
  batch_size: 500

# ✅ Fallback Strategy
fallback:
  enable: true
  strategy:
    - check_alternatives
    - requirement_capture
  requirement_capture:
    imp_fields:
      - location
      - property_type_name
      - number_of_bedrooms
      - rent_charge
      - furnishing_status
      - nearby_landmarks
      - building_name
      - rent_type_name
    save_to_table: user_requirements
    ask_confirmation: true

memory:
  type: llm
  strategy:
    keep_last_turns: 10 # keep last 10 exchanges raw
    summarize_older: true # ask LLM to summarize older history
    ttl_seconds: 900 # expire after 15 min of inactivity

# Requirement gathering configuration (NEW API FORMAT)
requirement_gathering:
  endpoint: http://localhost:5000/backend/api/v1/admin/user-request-mappings/request-response
  retry_attempts: 3
  retry_delay: 2
  enabled: true
  auto_save_on_conversation_end: true
  ask_user_confirmation: true
  # Essential property fields that MUST be collected before sending
  essential_fields:
    - location               # Location (emirate/city/community)
    - property_type_name     # Property type (apartment/villa/studio)
    - number_of_bedrooms     # Number of bedrooms
    - rent_charge            # Budget/Annual rent
    - furnishing_status      # Furnished/Semi-furnished/Unfurnished
    - amenities              # Required amenities (gym, pool, parking, etc.)
    - lease_duration         # Lease duration (1 year, 2 years, etc.)
  # Legacy field (kept for backward compatibility)
  priority_fields:
    - location
    - property_type_name
    - number_of_bedrooms
    - rent_charge
    - furnishing_status
    - amenities
    - lease_duration
