app:
  name: "RAG Pipeline"
  host: 0.0.0.0
  port: 8000
  eager_init: true
logging:
  level: INFO
database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  table: properties
  id_column: id
  columns:
    - property_title
    - property_description
    - emirate
    - city
    - district
    - property_type_id
    - rent_charge
    - lease_duration
    - amenities

chunking:
  chunk_size: 500
  chunk_overlap: 50

embedding:
  provider: google
  model: ${GOOGLE_GEMINI_EMBED_MODEL}
  api_key: ${GOOGLE_API_KEY}
  batch_size: 64

vector_db:
  provider: elasticsearch
  hosts:
    - ${ELASTIC_HOST:-http://localhost:9200}
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  index: rag_properties
  similarity: cosine
  refresh_on_write: false

retrieval:
  top_k: 5
  num_candidates_multiplier: 8
  filter_fields:
    - city
    - emirate
    - property_type_id

llm:
  provider: google
  model: ${GOOGLE_GEMINI_MODEL}
  temperature: 0.2
  max_output_tokens: 1024

ingestion:
  batch_size: 500
