app:
  name: "RAG Pipeline"
  host: 0.0.0.0
  port: 8080
  eager_init: false

logging:
  level: INFO

database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  table: properties
  id_column: id
  columns:
    - id
    - property_title
    - property_description
    - nearby_landmarks
    - building_name
    - emirate
    - city
    - district
    - community
    - subcommunity
    - property_type_id
    - rent_type_id
    - furnishing_status
    - number_of_bedrooms
    - number_of_bathrooms
    - property_size
    - rent_charge
    - bnb_verification_status
    - premiumBoostingStatus
    - carouselBoostingStatus
    - property_status
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - beach_access
    - jogging_cycling_tracks
    - mosque_nearby
    - media

  # ✅ Embedding only descriptive text fields
  embedding_columns:
    - property_title
    - property_description
    - building_name
    - nearby_landmarks

  # ✅ Filters for structured fields
  field_types:
    property_title: text
    property_description: text
    nearby_landmarks: text
    building_name: text

    emirate: keyword
    city: keyword
    district: keyword
    community: keyword
    subcommunity: keyword

    furnishing_status: keyword
    property_type_id: keyword
    rent_type_id: keyword

    number_of_bedrooms: integer
    number_of_bathrooms: integer
    property_size: float
    rent_charge: float

    bnb_verification_status: keyword
    premiumBoostingStatus: keyword
    carouselBoostingStatus: keyword
    property_status: keyword

    maids_room: boolean
    security_available: boolean
    concierge_available: boolean
    central_ac_heating: boolean
    elevators: boolean
    balcony_terrace: boolean
    storage_room: boolean
    laundry_room: boolean
    gym_fitness_center: boolean
    childrens_play_area: boolean
    bbq_area: boolean
    pet_friendly: boolean
    smart_home_features: boolean
    beach_access: boolean
    jogging_cycling_tracks: boolean
    mosque_nearby: boolean
    media: json

chunking:
  chunk_size: 500
  chunk_overlap: 50
  unit: token

embedding:
  provider: google
  model: ${LLM_EMBED_MODEL_NAME}
  api_key: ${LLM_MODEL_API_KEY}
  batch_size: 64

vector_db:
  provider: elasticsearch
  hosts:
    - ${VECTOR_DB_HOST}
  username: ${VECTOR_DB_USERNAME}
  password: ${VECTOR_DB_PASSWORD}
  index: rag_properties
  similarity: cosine
  refresh_on_write: false
  dims: 3072
  mapping_properties_key: properties

retrieval:
  top_k: 8
  num_candidates_multiplier: 20
  filter_fields:
    - emirate
    - city
    - district
    - community
    - subcommunity
    - property_type_id
    - rent_type_id
    - furnishing_status
    - number_of_bedrooms
    - number_of_bathrooms
    - rent_charge
    - property_size
    - bnb_verification_status
    - premiumBoostingStatus
    - carouselBoostingStatus
    - property_status
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - beach_access
    - jogging_cycling_tracks
    - mosque_nearby

llm:
  provider: google
  model: ${LLM_MODEL_NAME}
  temperature: 0.2
  max_output_tokens: 1024

ingestion:
  batch_size: 500

# ✅ Fallback Strategy
fallback:
  enable: true
  strategy:
    - ask_user_choice # ask if they want alternative search OR to provide requirements
    - check_alternatives # if yes → try budget/bedroom/location flexibility
    - requirement_capture # if no results, capture their requirement
  alternatives:
    budget_flex: 0.2 # allow +20% budget
    bedroom_flex: 1 # allow +/-1 bedroom
    nearby_communities: true
  requirement_capture:
    imp_fields:
      - location
      - property_type_id
      - number_of_bedrooms
      - rent_charge
      - furnishing_status
      - nearby_landmarks
      - building_name
      - rent_type_id
    save_to_table: user_requirements
    ask_confirmation: true

memory:
  type: llm
  strategy:
    keep_last_turns: 10 # keep last 10 exchanges raw
    summarize_older: true # ask LLM to summarize older history
    ttl_seconds: 900 # expire after 15 min of inactivity

