app:
  name: "RAG Pipeline"
  host: 0.0.0.0
  port: 8080
  eager_init: false

logging:
  level: INFO

database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  table: properties
  id_column: id
  columns:
    - id
    # ✅ Embedding fields
    - property_title
    - property_description
    - nearby_landmarks
    - building_name

    # ✅ Filter fields (structured search)
    - emirate
    - city
    - district
    - community
    - subcommunity
    - property_type_id
    - rent_type_id
    - furnishing_status
    - number_of_bedrooms
    - number_of_bathrooms
    - property_size
    - rent_charge
    - bnb_verification_status
    - premiumBoostingStatus
    - carouselBoostingStatus
    - property_status

    # ✅ Amenity fields (for embedding)
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - beach_access
    - jogging_cycling_tracks
    - mosque_nearby

  # Optional: explicitly control which columns are used to compose the embedding text
  # Fields that users naturally ask about when searching for properties to lease
  embedding_columns:
    # Core property identification
    - property_title
    - property_description
    - building_name

    # Location information (most important for property search)
    - emirate
    - city
    - community
    - subcommunity
    - nearby_landmarks

    # Property characteristics (what users filter by)
    - furnishing_status
    - property_type_id # Will be resolved to property type name
    - rent_type_id # Will be resolved to rent type name

    # Amenities and features (what users ask about)
    - maids_room
    - security_available
    - concierge_available
    - central_ac_heating
    - elevators
    - balcony_terrace
    - storage_room
    - laundry_room
    - gym_fitness_center
    - childrens_play_area
    - bbq_area
    - pet_friendly
    - smart_home_features
    - beach_access
    - jogging_cycling_tracks
    - mosque_nearby

  # Optional: explicit field type hints for dynamic ES mappings
  # Supported: keyword, text, integer, float
  field_types:
    # Text fields for embedding
    property_title: text
    property_description: text
    nearby_landmarks: text
    building_name: text
    emirate: text
    city: text
    community: text
    subcommunity: text
    furnishing_status: text

    # Boolean fields for amenities (will be converted to text for embedding)
    maids_room: text
    security_available: text
    concierge_available: text
    central_ac_heating: text
    elevators: text
    balcony_terrace: text
    storage_room: text
    laundry_room: text
    gym_fitness_center: text
    childrens_play_area: text
    bbq_area: text
    pet_friendly: text
    smart_home_features: text
    beach_access: text
    jogging_cycling_tracks: text
    mosque_nearby: text

    # Filter fields (keyword for fast filtering)
    district: keyword
    property_type_id: keyword
    rent_type_id: keyword
    number_of_bedrooms: integer
    number_of_bathrooms: integer
    property_size: float
    rent_charge: float
    bnb_verification_status: keyword
    premiumBoostingStatus: keyword
    carouselBoostingStatus: keyword
    property_status: keyword

chunking:
  chunk_size: 500
  chunk_overlap: 50
  unit: token # "token" or "char"

embedding:
  provider: google
  model: ${LLM_EMBED_MODEL_NAME}
  api_key: ${LLM_MODEL_API_KEY}
  batch_size: 64

vector_db:
  provider: elasticsearch
  hosts:
    - ${VECTOR_DB_HOST}
  username: ${VECTOR_DB_USERNAME}
  password: ${VECTOR_DB_PASSWORD}
  index: rag_properties
  similarity: cosine
  refresh_on_write: false
  dims: 3072
  mapping_properties_key: properties

retrieval:
  top_k: 8
  num_candidates_multiplier: 20
  filter_fields:
    - emirate
    - city
    - district
    - community
    - subcommunity
    - property_type_id
    - rent_type_id
    - furnishing_status
    - number_of_bedrooms
    - number_of_bathrooms
    - rent_charge
    - property_size
    - bnb_verification_status
    - premiumBoostingStatus
    - carouselBoostingStatus
    - property_status

llm:
  provider: google
  model: ${LLM_MODEL_NAME}
  temperature: 0.2
  max_output_tokens: 1024

ingestion:
  batch_size: 500
